version: '2'

services:

  ie-api:
    container_name: ie-api
    tty: true
    image: bitnami/laravel:6.20.1
    ports:
      - 8001:3000
    networks:
      - ie-network
    volumes:
      - ./:/app
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}

networks:
  ie-network:
    external: true
